# Site settings
title: Luke Waite
email: lwaite@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lukewaite.github.io" # the base hostname & protocol for your site
twitter_username: lukewaite
github_username:  lukewaite

# Build settings
markdown: kramdown
